# Generated by Django 2.2 on 2020-07-19 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_orders_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity_ever_sold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_ever_stocked',
            field=models.IntegerField(default=0),
        ),
    ]
